name: kbo_analytics
version: 1.0.0
config-version: 2

profile: kbo_analytics

model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]

models:
  kbo_analytics:
    staging:
      +materialized: table
